-- ============================================================================
-- InvoiceRapid PRO — One-shot bundle to apply 3 migrations
-- Date: 2026-06-21
-- Author: ZKR Studio (auto-generated by Claude Code)
--
-- Aplica en una transacción los cambios de:
--   1. `20260621000000_add_referral_ad_thresholds.sql`     → INSERT 2 keys
--   2. `20260621000001_add_monthly_free_invoice_limit.sql`  → INSERT 1 key
--   3. `20260621000002_invoice_rpc_dynamic_limit.sql`      → CREATE OR REPLACE fn
--
-- USO:
--   Path A (rápido, recomendado):
--     - Abre https://supabase.com/dashboard/project/rvolqqtlmdyggrhfzwip/sql/new
--     - Pega TODO este archivo (Ctrl+A → Ctrl+C → Ctrl+V) en el editor
--     - Pulsa Run
--     - Tiempo total: ~30 segundos
--
-- IDEMPOTENTE: cada INSERT usa `ON CONFLICT (key) DO NOTHING`, así que aunque
-- se ejecute varias veces no duplica filas. La función se reemplaza atómicamente
-- con CREATE OR REPLACE.
--
-- PATH COMPLETO NO TOCA EL HISTORIAL DE MIGRATIONS:
-- Este es un script auxiliar aislado en /scripts/, NO va en /supabase/migrations/
-- para no confundir al CLI de Supabase (`supabase db push`). Los archivos
-- originales en /supabase/migrations/ son los que el CLI rastrea y los que
-- debes mantener como fuente de verdad.
-- ============================================================================

BEGIN;

-- ── Migration #1: app_config thresholds para referidos + interstitial ─────
INSERT INTO public.app_config (key, value) VALUES
  ('referral_required_count', '2'),
  ('interstitial_every_n_actions', '3')
ON CONFLICT (key) DO NOTHING;

-- ── Migration #2: app_config threshold para facturas gratuitas ──────────
INSERT INTO public.app_config (key, value) VALUES
  ('monthly_free_invoice_limit', '5')
ON CONFLICT (key) DO NOTHING;

-- ── Migration #3: reemplazar check_and_increment_invoice para leer ─────
-- dinámico el límite desde app_config. Esto convierte a Postgres en la
-- única fuente de verdad del enforcing (antes estaba hardcoded := 5).
--
-- SECURITY DEFINER: la función se ejecuta como superuser → puede leer
-- app_config sin tropezarse con RLS (sólo usuarios autenticados).
CREATE OR REPLACE FUNCTION check_and_increment_invoice(
  p_user_id UUID,
  p_month TEXT,
  p_mode TEXT DEFAULT 'increment'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_current_count INTEGER;
  v_limit INTEGER := 5; -- default conservador si app_config no está disponible
  v_result JSONB;
BEGIN
  -- 1. Leer el límite desde app_config (single source of truth).
  --    Si no existe o el valor es inválido, caer al default 5.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
     WHERE table_schema = 'public' AND table_name = 'app_config'
  ) THEN
    v_limit := 5;
  ELSE
    BEGIN
      SELECT value::INTEGER
        INTO v_limit
        FROM app_config
       WHERE key = 'monthly_free_invoice_limit';

      IF v_limit IS NULL OR v_limit < 0 THEN
        RAISE WARNING 'app_config.monthly_free_invoice_limit is null or negative (%), using default 5', v_limit;
        v_limit := 5;
      END IF;
    EXCEPTION
      -- 22P02 = invalid_text_representation: 'value::INTEGER' sobre texto
      -- basura (admin escribió 'five' por error). NO usamos WHEN OTHERS
      -- para que errores reales burbujeen a los logs de Supabase.
      WHEN invalid_text_representation THEN
        RAISE WARNING 'app_config.monthly_free_invoice_limit no es entero válido, usando default 5';
        v_limit := 5;
    END;
  END IF;

  -- 2. Asegurar que existe la fila del contador (upsert silencioso)
  INSERT INTO invoice_counters (user_id, month, invoice_count)
  VALUES (p_user_id, p_month, 0)
  ON CONFLICT (user_id, month) DO NOTHING;

  -- 3. Leer el contador actual con bloqueo FOR UPDATE
  SELECT invoice_count INTO v_current_count
    FROM invoice_counters
   WHERE user_id = p_user_id
     AND month = p_month
   FOR UPDATE;

  -- 4. Si es solo check, devolver sin modificar
  IF p_mode = 'check' THEN
    v_result := jsonb_build_object(
      'canCreate', v_current_count < v_limit,
      'isPro', false,
      'currentCount', v_current_count,
      'limit', v_limit
    );
    RETURN v_result;
  END IF;

  -- 5. Si ya alcanzó el límite, rechazar
  IF v_current_count >= v_limit THEN
    v_result := jsonb_build_object(
      'canCreate', false,
      'isPro', false,
      'currentCount', v_current_count,
      'limit', v_limit
    );
    RETURN v_result;
  END IF;

  -- 6. Incrementar atómicamente
  UPDATE invoice_counters
     SET invoice_count = v_current_count + 1,
         updated_at = NOW()
   WHERE user_id = p_user_id
     AND month = p_month;

  v_result := jsonb_build_object(
    'canCreate', true,
    'isPro', false,
    'currentCount', v_current_count + 1,
    'limit', v_limit
  );

  RETURN v_result;
END;
$$;

COMMENT ON FUNCTION check_and_increment_invoice(UUID, TEXT, TEXT) IS
  'Atomic check + increment of monthly free invoice counter. Limit read from app_config.monthly_free_invoice_limit on each call. SECURITY DEFINER bypasses RLS on app_config. 2026-06-21: dynamic limit (was hardcoded := 5).';

COMMIT;

-- ============================================================================
-- QUERIES DE VERIFICACIÓN (ejecutar manualmente después del bundle para
-- confirmar que todo se aplicó bien; NO las metas dentro de BEGIN/COMMIT):
-- ============================================================================
-- SELECT key, value, updated_at FROM public.app_config ORDER BY key;
--   → deberías ver 4 filas: interstitial_every_n_actions=3,
--     max_rewarded_ads_per_month=1, monthly_free_invoice_limit=5,
--     referral_required_count=2
--
-- SELECT proname, prosecdef FROM pg_proc WHERE proname = 'check_and_increment_invoice';
--   → prosecdef debe ser `t` (SECURITY DEFINER activo)
--
-- SELECT check_and_increment_invoice(
--   (SELECT id FROM auth.users LIMIT 1),  -- ⚠️ sólo en dev
--   to_char(now(), 'YYYY-MM'),
--   'check'
-- );
--   → debe devolver JSONB con `limit` = el valor actual en app_config
-- ============================================================================
